units:
  offset_x: 100
  offset_y: -100
  kx: cx
  ky: cy
  pp: 1.9999
  thumb_angle: 24
  thumb_shift: 2.5001
  pinky_stagger: ky*1/8
  ring_stagger: ky*4/8
  middle_stagger: ky*1/8
  index_stagger: -ky*2/8
  inner_stagger: -ky*2/8
points:
  key:
    width: kx
    height: ky
  zones:
    fingers:
      anchor:
        shift: [offset_x-kx/2, offset_y-(1.5ky+pinky_stagger+ring_stagger+middle_stagger)]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        outerleft:
          key:
            column_net: C1
          rows.middle:
            tags: left
          rows.bottom:
            tags: [large, left]
            adjust:
              rotate: 90
              shift: [0.5, -(0.25kx + 0.5)]
          rows.thumb.skip: true
        outerright:
          key:
            spread: 0
            column_net: C1
          rows.top.skip: true
          rows.middle:
            tags: [large, right]
            shift: [0, (0.25kx + 0.5)]
            adjust:
              rotate: 90
              shift: [0.5, 0]
          rows.bottom:
            tags: right
            shift: [0, -(0.5kx + 1)]
            adjust:
              rotate: 180
          rows.thumb.skip: true
        pinky:
          key:
            stagger: pinky_stagger
            column_net: C2
        ring:
          key:
            stagger: ring_stagger
            column_net: C3
        middle:
          key:
            stagger: middle_stagger
            column_net: C4
        index:
          key:
            stagger: index_stagger
            column_net: C5
        inner:
          key:
            stagger: inner_stagger
            column_net: C6
          rows.thumb.adjust:
            orient: -thumb_angle
            shift: [thumb_shift, -thumb_shift]
      rows:
        thumb:
          row_net: R1
        bottom:
          row_net: R2
        middle:
          row_net: R3
        top:
          row_net: R4
outlines:
  keys:
    - what: rectangle
      where: -large
      size: [kx-0.5, ky-0.5]
    - what: rectangle
      where: large
      size: [1.5kx-0.5, ky-0.5]
  plate:
    - what: rectangle
      where: [[/^fingers.*/, -right]]
      size: [kx+2pp, ky+2pp]
      fillet: 1
    - what: rectangle
      where: [[/^fingers.*/, large]]
      size: [1.5kx+2pp, ky+3pp]
      fillet: 1
    - what: rectangle
      where: fingers_inner_bottom
      size: [kx+2pp, ky+2pp]
      adjust:
        shift: [0, -5]
      fillet: 1
    - what: rectangle
      where: fingers_inner_thumb
      size: [kx+2pp, ky+2pp]
      adjust:
        shift: [-7, 0]
      fillet: 5
    - what: rectangle
      where: /^fingers.*/
      size: [14, 14]
      operation: subtract
  mainboard-outline:
    - what: rectangle
      where: [[/^fingers.*/, -large]]
      size: [kx, ky]
      fillet: 1
    - what: rectangle
      where: [[/^fingers.*/, large]]
      size: [1.5kx, ky+pp]
      fillet: 1
    - what: rectangle
      where: fingers_inner_bottom
      size: [kx, ky]
      adjust:
        shift: [0, -(ky-1)]
      fillet: 1
  combo:
    - name: plate
    - operation: stack
      name: mainboard-outline
pcbs:
  mainboard:
    outlines:
      main:
        outline: mainboard-outline
    footprints:
      switch:
        what: ceoloide/switch_choc_v1_v2
        where: [[/^fingers.*/, -left, -right]]
        params:
          side: F
          choc_v2_support: false
          hotswap: false
          reversible: true
          solder: true
          include_corner_marks: true
          switch_3dmodel_filename: "${KIPRJMOD}/../models/SW_Kailh_Choc_V1.wrl"
          from: "{{column_net}}"
          to: "{{colrow}}"
      switch-left:
        what: ceoloide/switch_choc_v1_v2
        where: [[/^fingers.*/, left]]
        params:
          side: B
          choc_v2_support: false
          hotswap: false
          reversible: false
          solder: true
          include_corner_marks: true
          switch_3dmodel_filename: "${KIPRJMOD}/../models/SW_Kailh_Choc_V1.wrl"
          switch_3dmodel_xyz_rotation: [180, 0, 0]
          switch_3dmodel_xyz_offset: [0, 0, -1.6]
          from: "{{column_net}}"
          to: "outer_{{row}}"
      switch-right:
        what: ceoloide/switch_choc_v1_v2
        where: [[/^fingers.*/, right]]
        params:
          side: F
          choc_v2_support: false
          hotswap: false
          reversible: false
          solder: true
          include_corner_marks: true
          switch_3dmodel_filename: "${KIPRJMOD}/../models/SW_Kailh_Choc_V1.wrl"
          switch_3dmodel_xyz_rotation: [180, 0, 0]
          switch_3dmodel_xyz_offset: [0, 0, -1.6]
          from: "{{column_net}}"
          to: "outer_{{row}}"
      diode:
        what: ceoloide/diode_tht_sod123
        where: [[/^fingers.*/, -left, -right]]
        params:
          reversible: true
          include_thru_hole_smd_pads: true
          diode_3dmodel_filename: "${KICAD9_3DMODEL_DIR}/Diode_SMD.3dshapes/D_SOD-123.wrl"
          diode_3dmodel_xyz_rotation: [180, 0, 0]
          diode_3dmodel_xyz_offset: [0, 0, -1.6]
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [3, -3.5]
          rotate: 90
      diode-outer-middle:
        what: ceoloide/diode_tht_sod123
        where: fingers_outerleft_middle
        params:
          reversible: true
          include_thru_hole_smd_pads: true
          diode_3dmodel_filename: "${KICAD9_3DMODEL_DIR}/Diode_SMD.3dshapes/D_SOD-123.wrl"
          diode_3dmodel_xyz_rotation: [180, 0, 0]
          diode_3dmodel_xyz_offset: [0, 0, -1.6]
          from: "outer_{{row}}"
          to: "{{row_net}}"
        adjust:
          shift: [5, -8]
          rotate: 90
      diode-outer-bottom:
        what: ceoloide/diode_tht_sod123
        where: fingers_outerright_bottom
        params:
          reversible: true
          include_thru_hole_smd_pads: true
          diode_3dmodel_filename: "${KICAD9_3DMODEL_DIR}/Diode_SMD.3dshapes/D_SOD-123.wrl"
          diode_3dmodel_xyz_rotation: [180, 0, 0]
          diode_3dmodel_xyz_offset: [0, 0, -1.6]
          from: "outer_{{row}}"
          to: "{{row_net}}"
        adjust:
          shift: [-5, -8]
          rotate: -90
      connector:
        what: gctConnector-reversible
        where: fingers_middle_top
        params:
          P1: GND
          P2: C1
          P3: C2
          P4: C3
          P5: C4
          P6: C5
          P7: C6
          P8: R1
          P9: R2
          P10: R3
          P11: R4
          P12: GND
          side: B
        adjust:
          shift: [-6.5, -7.5]
      via1:
        what: via
        where: fingers_middle_top
        adjust.shift: [-9, -10.5]
        params.net: C1
      via2:
        what: via
        where: fingers_middle_top
        adjust.shift: [-8, -10.5]
        params.net: C2
      via3:
        what: via
        where: fingers_middle_top
        adjust.shift: [-7, -10.5]
        params.net: C3
      via4:
        what: via
        where: fingers_middle_top
        adjust.shift: [-6, -10.5]
        params.net: C4
      via5:
        what: via
        where: fingers_middle_top
        adjust.shift: [-5, -10.5]
        params.net: C5
      via6:
        what: via
        where: fingers_middle_top
        adjust.shift: [-4, -10.5]
        params.net: C6
      via7:
        what: via
        where: fingers_middle_top
        adjust.shift: [-8, -3.5]
        params.net: R1
      via8:
        what: via
        where: fingers_middle_top
        adjust.shift: [-7, -3.5]
        params.net: R2
      via9:
        what: via
        where: fingers_middle_top
        adjust.shift: [-6, -3.5]
        params.net: R3
      via10:
        what: via
        where: fingers_middle_top
        adjust.shift: [-5, -3.5]
        params.net: R4
